name: Whishper GPU Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    name: Build
    runs-on: Scottsdale-4

    steps:
      - name: Free disk space
        run: |
          sudo docker rmi $(docker image ls -aq) >/dev/null 2>&1 || true
          sudo rm -rf /usr/share/dotnet  || true
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
          sudo rm -rf /usr/local/lib/android /opt/ghc /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup /usr/lib/jvm || true
          echo "some directories deleted"

      - name: Enable Corepack
        run: corepack enable

      - name: Set pnpm version
        run: corepack prepare pnpm@8.6.0 --activate

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Release Docker images
        uses: docker/build-push-action@v5
        if: ${{ !github.event.release.prerelease }}
        with:
          context: .
          file: ./Dockerfile.gpu
          platforms: linux/amd64,linux/arm64
          push: true
          no-cache: true
          tags: |
            ${{ format('{0}/whishper:{1}-gpu', secrets.DOCKERHUB_USERNAME, github.event.release.tag_name) }}
            ${{ format('{0}/whishper:latest-gpu', secrets.DOCKERHUB_USERNAME) }}
        
      - name: Build and push Prerelease Docker images
        uses: docker/build-push-action@v5
        if: ${{ github.event.release.prerelease }}
        with:
          context: .
          file: ./Dockerfile.gpu
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ format('{0}/whishper:{1}-gpu', secrets.DOCKERHUB_USERNAME, github.event.release.tag_name) }}
        

